### ISSUE TITLE
generation of poco classes with T4 templates ?

### ISSUE THREAD

**Issue by eakova** [ThatRendle/Simple.Data#173]

**Comment by ThatRendle** [comment]
Some form of POCO generation is planned for the Simple.Data.Pad application: http://github.com/markrendle/Simple.Data.Pad.

**Comment by eakova** [comment]
Hello Mark , thnx for suggestion ..
If I use the compiled exe in release folder , it does not create an error but it does not connect and run any query on my local host ( sql server end r2 64 bit )
When I try to build and run , I see the error below on main window.

System.Windows.Markup.XamlParseException: 'The invocation of the constructor on type 'Simple.Data.Pad.MainWindow' that matches the specified binding constraints threw an exception.' Line number '6' and line position '9'. ---> System.TypeInitializationException: The type initializer for 'Simple.Data.Pad.AutoCompleter' threw an exception. ---> System.NotImplementedException: We don't support locales other than english yet
   at System.Data.Entity.Design.PluralizationServices.PluralizationService.CreateService(CultureInfo culture)
   at Simple.Data.Pad.Prettifier..ctor() in C:\Users\Administrator\Desktop\markrendle-Simple.Data.Pad-6c4db80\Simple.Data.Pad\Prettifier.cs:line 14
   at Simple.Data.Pad.AutoCompleter..cctor() in C:\Users\Administrator\Desktop\markrendle-Simple.Data.Pad-6c4db80\Simple.Data.Pad\AutoCompleter.cs:line 18
   --- End of inner exception stack trace ---
   at Simple.Data.Pad.AutoCompleter..ctor(ISchemaProvider schemaProvider)
   at Simple.Data.Pad.MainViewModel..ctor() in C:\Users\Administrator\Desktop\markrendle-Simple.Data.Pad-6c4db80\Simple.Data.Pad\MainViewModel.cs:line 22
   at Simple.Data.Pad.MainWindow..ctor() in C:\Users\Administrator\Desktop\markrendle-Simple.Data.Pad-6c4db80\Simple.Data.Pad\MainWindow.xaml.cs:line 34
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
