### ISSUE TITLE
Cannot implicitly convert type 'Simple.Data.SimpleRecord' to 'Randi.Business.Entities.Company'

### ISSUE THREAD

**Issue by jhovgaard** [ThatRendle/Simple.Data#183]
Hi,

I'm having a huge issue trying to get all rows of a table. Here's the code causing the exception:

``` c#
public List<Company> FindAll() {
    return Database.Companies.All().ToList<Company>();
}
```

The `Database` object is defined in my ctor like this:

``` c#
protected Service() {
    Database = Simple.Data.Database.Open();
}
```

The following exception gets thrown:

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'Simple.Data.SimpleRecord' to 'Randi.Business.Entities.Company'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Simple.Data.CastEnumerable`1.CastEnumerator.get_Current() in C:\Dropbox\Forks\Simple.Data\Simple.Data\CastEnumerable.cs:line 25
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Simple.Data.SimpleQuery.ToList[T]() in C:\Dropbox\Forks\Simple.Data\Simple.Data\SimpleQuery.cs:line 594
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Randi.Business.Services.CompanyService.FindAll() in C:\Dropbox\Privat\Randi\src\Randi.Business\Services\CompanyService.cs:line 22
```

If I change the method to call `FindAll()` instead of `All()` I get another stack:

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Randi.Business.Services.CompanyService.FindAll() in C:\Dropbox\Privat\Randi\src\Randi.Business\Services\CompanyService.cs:line 22
```

Hopefully this is my fault, and not a bug, but I really can't seem to figure out what I'm doing wrong.

I'm using MSSQL 2008, and the table I'm querying on is like this:

``` SQL
CREATE TABLE [dbo].[Companies](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [CreatedDate] [datetime] NOT NULL,
    [Name] [nvarchar](255) NOT NULL,
    [OwnerPersonId] [int] NULL,
    [BankBalance] [decimal](19, 5) NOT NULL,
    [PlotId] [int] NOT NULL,
    [ProductionType] [int] NOT NULL,
 CONSTRAINT [PK_Companies] PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
```

Thanks!

**Comment by ThatRendle** [comment]
I need to improve the error on this, but it is usually because there is no
default constructor on the entity type. Although in one recent instance it
was because the type had all public fields instead of properties.
On Apr 29, 2012 6:49 PM, "jhovgaard" <
reply@reply.github.com>
wrote:

**Comment by jhovgaard** [comment]
Oh no, it was that simple, you're right! 

Thanks a million for the quick answer :-)
