### ISSUE TITLE
Eager loading null children and ArgumentOutOfRangeException 

### ISSUE THREAD

**Issue by maniserowicz** [ThatRendle/Simple.Data#211]
I have 1:n relation (Role -> DefaultLevels), I query it like this:

``` C#
List<dynamic> currentAreas = tx.Roles.FindAllByRoleId(model.Id)
    .WithDefaultLevels()
    .ToList();
```

When role actually has some children, everything is fine. But when there is no "Default level" assigned to a Role, I get ArgumentOutOfRange exception when trying to get row.DefaultLevels.

It seems to work OK when I construct the query like this:

``` C#
List<dynamic> currentAreas = tx.Roles.FindAllByRoleId(model.Id)
    .WithMany(tx.Roles.DefaultLevels)
    .ToList();
```

More info:

```
Exception information: 
    Exception type: ArgumentOutOfRangeException 
    Exception message: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at Simple.Data.Ado.OptimizedDictionary`2.get_Item(TKey key)
   at Simple.Data.SimpleRecord.TryGetMember(GetMemberBinder binder, Object& result)
   at CallSite.Target(Closure , CallSite , Object )
```

**Comment by maniserowicz** [comment]
A little update: WithMany does not seem to work either

**Comment by ThatRendle** [comment]
That's an edge case with a problem around list capacity, which I've fixed now (I hope).
