### ISSUE TITLE
Security Exception in Medium trust

### ISSUE THREAD

**Issue by schappel** [ThatRendle/Simple.Data#220]
I have deployed the latest version of Simple.Data (0.17.1.1 from NuGet) into a shared hosting provider, and I am getting a SecurityException being fired when trying to create a database by name.  I believe that MEF is to blame here, but I am a bit lost on how to solve the issue.  Here is the stack trace:
System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessSecurityEngine.Check(CodeAccessPermission cap, StackCrawlMark& stackMark)
   at System.Security.CodeAccessPermission.Demand()
   at System.Reflection.RuntimeAssembly.VerifyCodeBaseDiscovery(String codeBase)
   at System.Reflection.RuntimeAssembly.GetName(Boolean copiedName)
   at System.Reflection.Assembly.GetName()
   at Simple.Data.MefHelper.IsSimpleDataAssembly(Assembly assembly)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at Simple.Data.MefHelper.CreateAppDomainContainer()
   at Simple.Data.MefHelper.Compose[T](String contractName)
   at Simple.Data.AdapterFactory.DoCreate(String adapterName, IEnumerable`1 settings)
   at Simple.Data.CachingAdapterFactory.<>c__DisplayClass1.<Create>b__0(String _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Simple.Data.CachingAdapterFactory.Create(String adapterName, IEnumerable`1 settings)
   at Simple.Data.AdapterFactory.Create(String adapterName, Object settings)
   at Simple.Data.DatabaseOpener.OpenNamedConnectionMethod(String connectionName)
   at Simple.Data.DatabaseOpener.OpenNamedConnection(String connectionName)
   at Simple.Data.Database.OpenNamedConnection(String connectionName)
   at JeldWenApps.Repositories.SqlRepository.get_AllApps() in D:\Projects\Jeld-Wen\iCat\Development\MMF003\Src\JeldWenApps\JeldWenApps.Repositories\SqlRepository.cs:line 24

**Comment by schappel** [comment]
It turns out that Assembly.GetName() actually requires IO access to get the filename of the assembly, which is triggering this security error.  I worked around this by replacing all Assembly.GetName() with assembly.FullName.Substring( 0, assembly.FullName.IndexOf( ",", StringComparison.OrdinalIgnoreCase ) )

**Comment by ThatRendle** [comment]
Right, thanks, I'll get that change into the core for release shortly.

Cheers,
Mark

**Comment by ThatRendle** [comment]
Fixed.
