### ISSUE TITLE
Simple.Data.UnresolvableObjectException: No matching table found, or insufficient permissions

### ISSUE THREAD

**Issue by qinking126** [ThatRendle/Simple.Data#352]
I deployed my application to theUAT server, got following error message.  I deployed hte same code to the dev server, everything works. since it works in dev, so DB and my code should be fine. it must be something else. what else can i check?

Simple.Data.UnresolvableObjectException: No matching table found, or insufficient permissions.
   at Simple.Data.Ado.Schema.TableCollection.Find(String tableName, String schemaName)
   at Simple.Data.Ado.AdoAdapterInserter.Insert(String tableName, IEnumerable`1 data, Boolean resultRequired)
   at Simple.Data.Commands.InsertCommand.InsertEntity(Object entity, DataStrategy dataStrategy, String tableName, ErrorCallback onError, Boolean resultRequired)
   at Simple.Data.Commands.InsertCommand.DoInsert(InvokeMemberBinder binder, Object[] args, DataStrategy dataStrategy, String tableName)
   at Simple.Data.Commands.InsertCommand.Execute(DataStrategy dataStrategy, DynamicTable table, InvokeMemberBinder binder, Object[] args)
   at Simple.Data.DynamicTable.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at Simple.Data.ObjectReference.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , XMLDataItem )
   at MsmqListener.DAL.DataRepository.InsertXMLData(XMLDataItem item) in c:\Projects\CFWinSvc\MsmqListener\DAL\DataRepository.cs:line 78

**Comment by skironDotNet** [comment]
Well, first make sure that your UAT have all tables from Dev :P I don't know maybe permissions, usually everything goes thru dbo.TableName, the object owner maybe someone else, and the DB credentials for this owner may have less privileges. That in case no errors accessing other tables than that one.
