### ISSUE TITLE
Simple.Data “No ADO Provider Found”

### ISSUE THREAD

**Issue by shailesh1984** [ThatRendle/Simple.Data#405]
I am getting below error when i modified to connection string.
connection string : connectionString="Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=DBName;Data Source=."

Sql Server 2017

Simple.Data.SimpleDataException
  HResult=0x80131500
  Message=No Ado Provider found.
  Source=Simple.Data
  StackTrace:
   at Simple.Data.MefHelper.Compose[T](String contractName)
   at Simple.Data.AdapterFactory.DoCreate(String adapterName, IEnumerable`1 settings)
   at Simple.Data.CachingAdapterFactory.<>c__DisplayClass1.<Create>b__0(String _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Simple.Data.CachingAdapterFactory.Create(String adapterName, IEnumerable`1 settings)
   at Simple.Data.AdapterFactory.Create(String adapterName, Object settings)
   at Simple.Data.DatabaseOpener.OpenConnectionMethod(String connectionString)
   at Simple.Data.DatabaseOpener.OpenConnection(String connectionString)
   at Simple.Data.Database.OpenConnection(String connectionString)
   at SkillsMatrix.Tests.Attributes.UsePersonAttribute..ctor() in D:\Works\SkillsMatrixTests\SkillsMatrix.Tests\Attributes\UsePersonAttribute.cs:line 23
   at System.RuntimeTypeHandle.CreateCaInstance(RuntimeType type, IRuntimeMethodInfo ctor)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at Xunit.Sdk.XunitTestCaseRunner.GetBeforeAfterTestAttributes() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestCaseRunner.cs:line 127
   at Xunit.Sdk.XunitTestCaseRunner.RunTestAsync() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestCaseRunner.cs:line 139
   at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestCaseRunner.cs:line 82

**Comment by jonas-stjernquist** [comment]
I get same error, found any solution?

Update: This solution helped me
https://github.com/markrendle/Simple.Data/issues/392#issuecomment-243420576
