### ISSUE TITLE
SqlDbType needs to be set in SqlCeParameter - SQL Compact 4 

### ISSUE THREAD

**Issue by charlescook** [ThatRendle/Simple.Data#77]
When the schema is created SQL column types are mapped onto members of the DbType enum. This loses significant information about the column. For example in SQL Compact 4 I want to use a SQL NTEXT column so that the field can contain more than 4000 characters. However the column type is mapped onto DbType.String and when an instance of IDbDataParameter is created the parameter type is set to NVarChar. This means that when I try to update a field with more than 4000 chars I get this error (stack trace below)

@p1 : String truncation: max=4000, len=10000, value='XXXXXXXXXX...

The underlying instance of SqlCeParameter needs to have it SqlDbType property set to SqlDbType.NText for the update to succeed.

This problem may apply to other SQL column types for Sql Compact 4 and possibly for Sql Server.

I investigated a fix for this and while it's straightforward to create a SqlCeColumn type deriving from Column, to store the SqlDbType when generating the schema, it appears non-trivial to plug in SqlCe-specific versions of CommandBuilder, ParameterTemplate, etc.  On the other hand there may be a simple fix I'm missing.

   at System.Data.SqlServerCe.SqlCeCommand.FillParameterDataBindings(Boolean verifyValue)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteNonQuery()
   at Simple.Data.Ado.AdoAdapter.TryExecute(IDbCommand command) in C:\temp\markrendle-Simple.Data-178e47f\Simple.Data.Ado\AdoAdapter.cs:line 259
   at Simple.Data.Ado.AdoAdapter.Execute(ICommandBuilder commandBuilder) in C:\temp\markrendle-Simple.Data-178e47f\Simple.Data.Ado\AdoAdapter.cs:line 241
   at Simple.Data.Ado.AdoAdapter.Update(String tableName, IDictionary`2 data, SimpleExpression criteria) in C:\temp\markrendle-Simple.Data-178e47f\Simple.Data.Ado\AdoAdapter.cs:line 209
   at Simple.Data.Database.Update(String tableName, IDictionary`2 data, SimpleExpression criteria) in C:\temp\markrendle-Simple.Data-178e47f\Simple.Data\Database.cs:line 110
   at Simple.Data.Commands.UpdateCommand.UpdateByKeyFields(String tableName, DataStrategy dataStrategy, Object entity, IEnumerable`1 keyFieldNames) in C:\temp\markrendle-Simple.Data-178e47f\Simple.Data\Commands\UpdateCommand.cs:line 46
   at Simple.Data.Commands.UpdateCommand.Execute(DataStrategy dataStrategy, DynamicTable table, InvokeMemberBinder binder, Object[] args) in C:\temp\markrendle-Simple.Data-178e47f\Simple.Data\Commands\UpdateCommand.cs:line 29
   at Simple.Data.DynamicTable.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result) in C:\temp\markrendle-Simple.Data-178e47f\Simple.Data\DynamicTable.cs:line 68
   at CallSite.Target(Closure , CallSite , Object , Foo )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at Program.Main(String[] args) in C:\temp\markrendle-Simple.Data-178e47f\TestNText\Program.cs:line 25
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by charlescook** [comment]
I have a workaround for this. I'll put in a pull request later today.

**Comment by ThatRendle** [comment]
Oops. I fixed it. It's in 0.9.3.1, on NuGet now.
