### ISSUE TITLE
Delete within transaction throws exception

### ISSUE THREAD

**Issue by saggett** [ThatRendle/Simple.Data#82]
The following code, run against a local database hosted by SQL Server 2008 R2:

```
    [Test]
    public void ShouldNotThrowAnException()
    {
        var db = Simple.Data.Database.OpenConnection(
            System.Configuration.ConfigurationManager.ConnectionStrings["default"].ConnectionString);
        using (var tx = db.BeginTransaction())
        {
            tx.MyTable.DeleteAll();
            tx.Commit();
        }
    }
```

Results in the exception:
System.InvalidOperationException : ExecuteNonQuery requires the command to have a transaction when the connection assigned to the command is in a pending local transaction.  The Transaction property of the command has not been initialized.
at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(DbAsyncResult result, String methodName, Boolean sendToPipe)
at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
at Simple.Data.Ado.AdoAdapter.TryExecute(IDbCommand command)
at Simple.Data.Ado.AdoAdapter.Execute(ICommandBuilder commandBuilder, IAdapterTransaction transaction)
at Simple.Data.Commands.DeleteAllCommand.Execute(DataStrategy dataStrategy, DynamicTable table, InvokeMemberBinder binder, Object[] args)
at Simple.Data.DynamicTable.TryInvokeMember(InvokeMemberBinder binder, Object[] args, ref Object result)
at Simple.Data.ObjectReference.TryInvokeMember(InvokeMemberBinder binder, Object[] args, ref Object result)
at CallSite.Target(Closure, CallSite, Object)
at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1<T0>(CallSite site, T0 arg0)
at DocumentDALFixture.ShouldNotThrowAnException() in DocumentDALFixture.cs

**Comment by ThatRendle** [comment]
Thanks for raising this, I will investigate.

On Fri, Sep 9, 2011 at 4:56 PM, saggett
reply@reply.github.com
wrote:

**Comment by ThatRendle** [comment]
Unbelievably, I had no test coverage at all for Delete. Now I have, and this is fixed in 0.9.6.

**Comment by benifie** [comment]
Firstly I want to say thanks for your contributions to the open source community with fantastic tools like Simple.Data I have a question regarding its usage I have a method that returns a test user from a DB table for use by a front end automation test. If the user is successfully returned, I wish to update the IsUsed column of this table from 0 to 1. I will like to lock the row after the select to ensure another test running in parallel does not also select this row My code snippet is below 

Table columns are Email, IsUsed, Id(Primary Key) 

Db = Database.OpenConnection(connectionstring); 

public String GetCustomer() 
{ 
using(var tx= Db.BeginTransaction()) 
{ 
var unusedCus = tx.TestUsers.FindByIsUsed(0); 
tx.TestUsers.UpdateByEmail(IsUsed: 1, Email: unusedCus.Email); 
tx.Commit(); 
return unusedCus.Email;
 }
 } 

(I have removed the try/catch block) 

Can you help confirm if the above code will meet my needs? Cheers

**Comment by ThatRendle** [comment]
Hi,

Yes, that code looks all right, although you'll want to check the unusedCus
for null before doing the update.

There is currently no way to lock the row on the select, although the next
release will have a ForUpdate clause for doing that.

Cheers,
Mark

On Wed, Jul 4, 2012 at 11:15 AM, benifie <
reply@reply.github.com
